services:
  unittcms:
    image: unittcms:latest
    build: .
    ports:
      - '9000:9000'
    environment:
      - PORT=9000
      - SECRET_KEY=your_secret_key_here
      - IS_DEMO=false # set to true to seed the database
    volumes:
      - db-data:/app/backend/database
      - ./backend/public/uploads:/app/backend/public/uploads

volumes:
  db-data:
